---
output: html_document
params:
  reto: NA
---

---
title: `r paste("Detalle", params$reto)`
---

```{r setup, include=FALSE}
# LIBRERIAS ####################################################################
library(odbc)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(glue)
library(kableExtra)
# CONFIGURACIONES GLOBALES #####################################################
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
con <- dbConnect(odbc::odbc(),
                 .connection_string = "Driver={PostgreSQL ANSI};Uid=ubuntu;Database=herbalife;", 
                 timeout = 10)

dbSendStatement(con, "SET search_path = reto21")
```

## Puntajes

```{r Puntajes}
consulta_sql<- glue("
            with cuenta_habitos as (
            	select
            	concepto,
            	tp.nombre_retador,
            	nombre_habito,
            	count(nombre_habito) as n
            	from tbl_registros_habitos trh inner join
            		tbl_participacion tp on trh.id_participacion = tp.id_participacion
            	group by concepto, tp.nombre_reto, tp.nombre_retador, nombre_habito
            	having tp.nombre_reto = '{params$reto}')
            select
            	nombre_retador,
            	'Habitos' as concepto,
            	sum(n * peso_habito)/21 * peso_concepto * 100 as puntaje
            from cuenta_habitos ch inner join
            	tbl_habitos th on ch.nombre_habito = th.nombre_habito inner join
            	tbl_conceptos tc on ch.concepto = tc.concepto
            group by nombre_retador, peso_concepto")
            puntaje_habitos <- dbGetQuery(con, consulta_sql)
            
            consulta_sql<- glue("
            with actividades as (
            	select
            		nombre_reto,
            		count(id_actividad) as tot
            	from tbl_actividades
                where actividad::varchar != 'Ceremonia'
            	group by nombre_reto
            	having nombre_reto = '{params$reto}')
            select
            	tp.nombre_retador,
            	'Actividades' as concepto,
            	count(id_actividad) / a.tot::numeric * tc.peso_concepto * 100 as puntaje
            from tbl_registros_actividades tra inner join
            	tbl_participacion tp on tra.id_participacion = tp.id_participacion inner join
            	actividades a on tp.nombre_reto = a.nombre_reto inner join
            	tbl_conceptos tc on tra.concepto = tc.concepto
            group by a.tot, tp.nombre_reto, tp.nombre_retador, tc.peso_concepto")
            puntaje_actividades <- dbGetQuery(con, consulta_sql)
            
            consulta_sql<- glue("
            with promedio_calificacion as (
            	with coaches as (
            		select 
            			count(nombre_coach) as num_coaches
            		from
            			tbl_coaches tc
            		where tc.permiso != 'Inactivo'
            	)
            	select
            		concepto,
            		tp.nombre_retador,
            		criterio_calificacion,
            		sum(calificacion / num_coaches::numeric) as prom
            	from tbl_registros_calificaciones trc inner join
            		tbl_participacion tp on trc.id_participacion = tp.id_participacion 
            		cross join coaches c
            	group by concepto, tp.nombre_reto, tp.nombre_retador, criterio_calificacion
            	having tp.nombre_reto = '{params$reto}'
            )
            select
            	nombre_retador,
            	'Calificacion' as concepto,
            	sum(prom * peso_criterio)/3 * tc.peso_concepto * 100 as puntaje
            from promedio_calificacion pc inner join
            	tbl_criterios_calificacion tcc on pc.criterio_calificacion = tcc.criterio_calificacion inner join
            	tbl_conceptos tc on pc.concepto = tc.concepto
            group by nombre_retador, tc.peso_concepto")
            puntaje_calificaciones <- dbGetQuery(con, consulta_sql)
            
            puntajes <- puntaje_habitos %>% 
                bind_rows(puntaje_actividades) %>% 
                bind_rows(puntaje_calificaciones) %>%
                group_by(nombre_retador) %>% 
                mutate(puntaje = if_else(puntaje < 0, 0, puntaje),
                       total = sum(puntaje, na.rm = TRUE)) %>%
                ungroup() %>% 
                rename(Retador = nombre_retador) %>% 
                rename_with(str_to_sentence) %>% 
                arrange(Retador, Concepto)
            
            puntajes %>% 
                ggplot(aes(x = Puntaje, y = reorder(Retador, Total), fill = Concepto)) +
                geom_col(position = "stack") +
                geom_text(aes(label = number(Total, accuracy = 0.01), x = Total), hjust = -0.5) +
                scale_x_continuous(limits = c(0,100), expand = expansion(add = c(0, 10))) +
                coord_cartesian(clip = "off") +
                labs(title = "Puntaje por Retador",
                     y = "Retador(a)") +
                theme_minimal() +
                theme(legend.position = "bottom")
            
            puntajes %>% 
                kbl() %>% 
                kable_paper(c("hover", "condensed", "responsive"), full_width = T) %>%
                column_spec(1, bold = T) %>%
                collapse_rows(columns = c(1,4), valign = "middle")
```
## Cuenta de Habitos por Retador

```{r habitos}
consulta_sql <- glue_sql("
    select
    	tp.nombre_retador,
    	trh.nombre_habito,
    	count(trh.nombre_habito) as n
    from tbl_registros_habitos trh inner join
    	tbl_participacion tp on trh.id_participacion = tp.id_participacion inner join
    	tbl_habitos th on trh.nombre_habito = th.nombre_habito 
    where tp.nombre_reto = {params$reto}
    group by tp.nombre_retador, trh.nombre_habito, th.id_habito
    order by tp.nombre_retador, th.id_habito", .con = con)
res <- dbGetQuery(con, consulta_sql)
if (nrow(res) > 0) {
    res %>% 
  pivot_wider(names_from = nombre_habito, values_from = n, id_cols = nombre_retador) %>% 
  rename(Retador = nombre_retador) %>%
  kbl() %>% 
  kable_paper(c("striped", "hover", "condensed", "responsive"), full_width = T)
}
```
## Registro de Asistencia a Actividades por Retador

```{r actividades}
consulta_sql <- glue_sql("
  select
  	ta.actividad, 
  	lower(ta.tiempo_actividad)::date::varchar as fecha,
  	tp.nombre_retador,
    tra.nombre_coach
  from tbl_registros_actividades tra inner join
  	tbl_participacion tp on tra.id_participacion = tp.id_participacion left join
  	tbl_actividades ta on tra.id_actividad = ta.id_actividad 
  where tp.nombre_reto = {params$reto}
  order by fecha, nombre_retador", .con = con)
res <- dbGetQuery(con, consulta_sql)
if (nrow(res) > 0) {
    res %>% 
  mutate(Actividad = paste(actividad, format(as.Date(fecha), "%d/%m/%Y"))) %>% 
  select(Actividad, Retador = nombre_retador, Registrador = nombre_coach) %>% 
  kbl() %>% 
  kable_paper(c("hover", "condensed", "responsive"), full_width = T) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = c(1,3), valign = "middle")
}
```

## Calificaciones por Retador

```{r}
consulta_sql <- glue_sql("
  select
		tp.nombre_retador,
		nombre_coach,
		criterio_calificacion,
		calificacion
	from tbl_registros_calificaciones trc inner join
		tbl_participacion tp on trc.id_participacion = tp.id_participacion inner join 
		tbl_retos tr on tp.nombre_reto = tr.nombre_reto 
	where tp.nombre_reto = {params$reto}
	order by nombre_retador, nombre_coach, criterio_calificacion", .con = con)
res <- dbGetQuery(con, consulta_sql)
if (nrow(res) > 0) {
    res %>% 
  mutate(calificacion = case_when(
                calificacion == -3 ~ "Mucho Peor",
                calificacion == -2 ~ "Peor",
                calificacion == -1 ~ "Ligeramente Peor",
                calificacion == 0 ~ "Igual",
                calificacion == 1 ~ "Ligeramente Mejor",
                calificacion == 2 ~ "Mejor",
                calificacion == 3 ~ "Mucho Mejor",
                TRUE ~ NA_character_
            )) %>% 
  rename(Retador = nombre_retador,
         Calificador = nombre_coach,
         Criterio = criterio_calificacion,
         Calificacion = calificacion) %>% 
  kbl() %>% 
  kable_paper(c("hover", "condensed", "responsive"), full_width = T) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "middle")
}
```

```{r disconnect}
dbDisconnect(con)
```

